name: Publishing qualification

on:
  push:
    paths:
      - 'publication.yaml'
      - 'course/**'
      - '.github/workflows/publishing.yml'
  pull_request:
    paths:
      - 'publication.yaml'
      - 'course/**'
      - '.github/workflows/publishing.yml'

jobs:
  publishing:
    uses: Ploos-AS/publishing/.github/workflows/reusable-book-validate.yml@v1
    with:
      metadata: publication.yaml
